import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import crypto from 'node:crypto';
import {transform} from 'esbuild';
const compiled=await transform(fs.readFileSync('lib/calculations.ts','utf8'),{loader:'ts',format:'esm',target:'es2022'});
const calc=await import('data:text/javascript;base64,'+Buffer.from(compiled.code).toString('base64'));
const row={studentId:'s',individual:[9.53846153846154,10,7,7,7,7,7,7,7],group:Array(9).fill(7),exam:7,project:10,direct:null,reinforcement:null,workshop:null};
assert.equal(calc.result(row).individual,7.61);assert.equal(calc.result(row).formative,5.11);assert.equal(calc.result(row).summative,2.55);assert.equal(calc.result(row).total,7.66);
assert.equal(calc.trunc(8.999),8.99);assert.equal(calc.result({...row,exam:8,project:8,direct:6}).improved,8);assert.equal(calc.result({...row,exam:8,project:8,direct:10}).improved,9);
assert.equal(calc.result({...row,exam:6,project:6,reinforcement:9,workshop:9}).improved,8);assert.equal(calc.result({...row,exam:null}).total,null);assert.equal(calc.result({...row,individual:Array(9).fill(null),group:Array(9).fill(null)}).formative,null);
assert.equal(calc.annual([7,8,null]),null);assert.equal(calc.annual([7.66,8,9]),8.22);assert.equal(calc.qualitative(null),'Pendiente');assert.equal(calc.qualitative(9.5),'A+');assert.equal(calc.qualitative(8.5),'A-');assert.equal(calc.status(4),'PIERDE AÑO');assert.equal(calc.status(4.01),'SUPLETORIO');assert.equal(calc.status(7),'APROBADO');assert.equal(calc.makeup(6,9),7);assert.equal(calc.makeup(6,null),null);
console.log('PASS: truncamiento, promedios, mejoras, pendientes, umbrales y supletorios.');
const origin='http://localhost:5173';
const signin=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});const adminCookie=signin.headers.get('set-cookie').split(';')[0];
async function request(path,body,cookie=adminCookie,method='POST'){const res=await fetch(origin+path,{method:body?method:'GET',headers:{Cookie:cookie,'Content-Type':'application/json',Origin:origin},body:body?JSON.stringify(body):undefined});return {status:res.status,data:await res.json()};}
assert.equal((await request('/api/workspace',undefined,'')).status,401);
const created=await request('/api/workspace',{action:'createInstitution',name:'QA · Institución '+Date.now(),year:'2026–2027'});assert.equal(created.status,200);const institution=created.data.id;
assert.equal((await request('/api/demo',{institution})).status,200);let w=(await request('/api/workspace?institution='+institution)).data;
assert.equal(w.records.filter(r=>r.kind==='gradebook').length,9);assert.equal(w.records.filter(r=>r.kind==='student').length,12);
const c=w.records.find(r=>r.kind==='course'&&r.track==='Ciencias'),tech=w.records.find(r=>r.kind==='course'&&r.track==='Técnico');
const memberRes=await request('/api/members',{institution,name:'Docente QA',email:'teacher-qa@example.test',role:'docente',status:'aprobada',tutorCourses:[c.id]});assert.equal(memberRes.status,200);const memberId=memberRes.data.id;
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(f=>f.isDirectory()?files(dir+'/'+f.name):[dir+'/'+f.name]);}
const sqlite=files('.wrangler/state/v3/d1').find(f=>f.endsWith('.sqlite'));
const token='qa-'+crypto.randomUUID(),hash=crypto.createHash('sha256').update(token).digest('hex');const user='qa-teacher-'+crypto.randomUUID();
const py=spawnSync('C:/Users/bvera/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',['-c',"import sqlite3,sys; c=sqlite3.connect(sys.argv[1]); c.execute('INSERT INTO sessions(id,user,email,name,expires) VALUES(?,?,?,?,?)',(sys.argv[2],sys.argv[3],'teacher-qa@example.test','Docente QA',int(sys.argv[4]))); c.commit()",sqlite,hash,user,String(Date.now()+3600000)]);if(py.status)throw Error(py.stderr.toString());
const teacherCookie='byron_session='+token;const tw=await request('/api/workspace?institution='+institution,undefined,teacherCookie);assert.equal(tw.status,200);assert(tw.data.records.some(r=>r.kind==='gradebook'&&r.course===c.id));assert(!tw.data.records.some(r=>r.kind==='gradebook'&&r.course===tech.id));
const g=w.records.find(r=>r.kind==='gradebook'&&r.course===c.id);const payload=JSON.parse(g.payload);
assert.equal((await request('/api/records',{institution,id:g.id,version:g.version,kind:g.kind,course:g.course,payload},teacherCookie)).status,403);
assert.equal((await request('/api/records',{institution,kind:'student',course:c.id,payload:{name:'No autorizado'}},teacherCookie)).status,403);
const update={institution,id:g.id,version:g.version,kind:g.kind,course:g.course,payload};assert.equal((await request('/api/records',update)).status,200);assert.equal((await request('/api/records',update)).status,409);
assert.equal((await request('/api/records',{institution,kind:'document',course:c.id,payload:{name:'Payload inválido',content:'Texto',owner:memberId}})).status,400);
assert.equal((await request('/api/workspace?institution=otra-institucion',undefined,teacherCookie)).status,403);
assert.equal((await request('/api/members',{institution,id:memberId,name:'Docente QA',email:'teacher-qa@example.test',role:'docente',status:'suspendida',tutorCourses:[c.id]})).status,200);
assert.equal((await request('/api/workspace?institution='+institution,undefined,teacherCookie)).status,403);
const backup=await request('/api/backup?institution='+institution);assert.equal(backup.status,200);assert(!JSON.stringify(backup.data).includes('refresh_token'));
const other=await request('/api/workspace',{action:'createInstitution',name:'QA · Restauración '+Date.now(),year:'2026–2027'});
const restored=await request('/api/restore',{institution:other.data.id,backup:backup.data});assert.equal(restored.status,200);const rw=await request('/api/workspace?institution='+other.data.id);assert.equal(rw.data.records.length,w.records.length);assert(rw.data.records.every(r=>r.institution===other.data.id));
assert.equal((await request('/api/google/start')).status,503);
const a=w.records.find(r=>r.kind==='assignment');
const exported=await fetch(origin+'/api/export?institution='+institution+'&id='+a.id+'&type=matrix',{headers:{Cookie:adminCookie}});assert.equal(exported.status,200);assert(exported.headers.get('content-disposition').includes('attachment'));
const ExcelJS=(await import('exceljs')).default,wb=new ExcelJS.Workbook();await wb.xlsx.load(await exported.arrayBuffer());assert.equal(wb.worksheets.length,7);assert(wb.getWorksheet('CONSOLIDADO'));assert(wb.getWorksheet('SUPLETORIO'));
const pdf=await fetch(origin+'/api/export?institution='+institution+'&id='+a.id+'&type=consolidated&format=pdf',{headers:{Cookie:adminCookie}});assert.equal(pdf.status,200);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,4).toString(),'%PDF');
const meeting=w.records.find(r=>r.kind==='meeting'),acta=await fetch(origin+'/api/export?institution='+institution+'&id='+meeting.id+'&type=acta&format=pdf',{headers:{Cookie:adminCookie}});assert.equal(acta.status,200);assert.equal(Buffer.from(await acta.arrayBuffer()).subarray(0,4).toString(),'%PDF');
console.log('PASS: identidad, persistencia, aislamiento, tutoría, denegación de edición ajena, conflictos de versión, suspensión y restauración.');
console.log('PASS: exportación XLSX con las siete hojas, consolidado PDF y acta PDF.');
