export type GradeRow={studentId:string,individual:(number|null)[],group:(number|null)[],exam:number|null,project:number|null,direct:number|null,reinforcement:number|null,workshop:number|null,makeup?:number|null,observation?:string};
const SCALE=1_000_000_000n;
function scaled(n:number){const s=n.toFixed(9);const [a,b]=s.split('.');return BigInt(a)*SCALE+BigInt(b);}
export function trunc(n:number,places=2){const d=10n**BigInt(places);return Number(scaled(n)*d/SCALE)/Number(d);}
export function mean(a:(number|null)[]){const v=a.filter((n):n is number=>typeof n==='number'&&Number.isFinite(n));if(!v.length)return null;return Number(v.reduce((s,n)=>s+scaled(n),0n)/BigInt(v.length))/Number(SCALE);}
function weighted(n:number,p:number){return Number(scaled(n)*scaled(p)/SCALE*100n/SCALE)/100;}
export function result(r:GradeRow,weight=70){const pi=mean(r.individual),pg=mean(r.group);const category=mean([pi===null?null:trunc(pi),pg===null?null:trunc(pg)]);const formative=category===null?null:weighted(category,weight/100);let base=r.exam!==null&&r.project!==null?trunc(mean([r.exam,r.project])!):null;let improved=base;if(base!==null){if(base>7&&base<9&&r.direct!==null)improved=trunc(Math.max(base,Math.min(9,mean([base,r.direct])!)));else if(base<7&&r.reinforcement!==null&&r.workshop!==null)improved=trunc(Math.max(base,mean([base,r.reinforcement,r.workshop])!));}const summative=improved===null?null:weighted(improved,(100-weight)/100);const total=formative===null||summative===null?null:Number((scaled(formative)+scaled(summative))/10_000_000n)/100;const complete=r.individual.length>0&&r.group.length>0&&r.individual.every(x=>x!==null)&&r.group.every(x=>x!==null)&&base!==null;return {individual:pi===null?null:trunc(pi),group:pg===null?null:trunc(pg),base,improved,formative,summative,total,complete,qualitative:qualitative(total)};}
export function qualitative(n:number|null){if(n===null)return 'Pendiente';return n>=9.5?'A+':n>=8.5?'A-':n>=7.5?'B+':n>=6.5?'B-':n>=5.5?'C+':n>=4.5?'C-':'D+';}
export function annual(values:(number|null)[]){return values.length===3&&values.every(x=>x!==null)?trunc(mean(values)!):null;}
export function status(n:number|null){return n===null?'Pendiente':n<4.01?'PIERDE AÑO':n>6.99?'APROBADO':'SUPLETORIO';}
export function makeup(n:number|null,e:number|null){return n===null?null:n>6.99?n:e===null?null:e>6.99?7:Math.max(n,e);}
