import {result,annual,status,qualitative,makeup,type GradeRow} from './calculations';
export async function matrixExport(institution:any,assignment:any,course:any,subject:any,teacher:any,students:any[],books:any[]){const ExcelJS=(await import('exceljs')).default;const wb=new ExcelJS.Workbook();wb.creator='Profe. Byron Gestión Docente';const heading=(name:string,title:string,headers:string[])=>{const ws=wb.addWorksheet(name);ws.addRow([institution.name]);ws.addRow([title]);ws.addRow(['Curso',course.name,'Asignatura',subject.name,'Docente',teacher.name]);ws.addRow(['Año lectivo',institution.year]);ws.addRow([]);const h=ws.addRow(headers);h.font={bold:true,color:{argb:'FFFFFFFF'}};h.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF122D4B'}};ws.views=[{state:'frozen',xSplit:2,ySplit:6}];ws.columns=headers.map((x,i)=>({width:i===1?42:Math.max(13,Math.min(22,x.length+2))}));ws.pageSetup={orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0};return ws;};const row=(sid:string,p:number):GradeRow|undefined=>books.find(b=>b.assignmentId===assignment.id&&b.period===p)?.rows?.find((r:GradeRow)=>r.studentId===sid);const out=(sid:string,p:number)=>{const r=row(sid,p);return r?result(r,institution.settings.formative):null;};
for(let p=1;p<=3;p++){const b=books.find(b=>b.assignmentId===assignment.id&&b.period===p),ni=b?.individualNames?.length||institution.settings.individualCount,ng=b?.groupNames?.length||institution.settings.groupCount;const ws=heading('INSUMOS '+['I','II','III'][p-1]+' PERIODO','CUADRO DE INSUMOS · '+p+' PERÍODO',['N.º','Estudiante',...Array.from({length:ni},(_,i)=>'Individual '+(i+1)),'Prom. individual',...Array.from({length:ng},(_,i)=>'Grupal '+(i+1)),'Prom. grupal','Formativa ponderada','Estado']);students.forEach((s,i)=>{const r=row(s.id,p),o=out(s.id,p);ws.addRow([i+1,s.name,...Array.from({length:ni},(_,j)=>r?.individual[j]??null),o?.individual??null,...Array.from({length:ng},(_,j)=>r?.group[j]??null),o?.group??null,o?.formative??null,o?.complete?'Completo':'Provisional']);});}
const sw=heading('NOTA EV SUM','EVALUACIÓN SUMATIVA Y MEJORAS',['N.º','Estudiante',...Array.from({length:3},(_,i)=>['Examen P'+(i+1),'Proyecto P'+(i+1),'Inicial P'+(i+1),'Mejora directa P'+(i+1),'Refuerzo P'+(i+1),'Taller P'+(i+1),'Definitiva P'+(i+1)]).flat()]);students.forEach((s,i)=>sw.addRow([i+1,s.name,...[1,2,3].flatMap(p=>{const r=row(s.id,p),o=out(s.id,p);return [r?.exam??null,r?.project??null,o?.base??null,r?.direct??null,r?.reinforcement??null,r?.workshop??null,o?.improved??null];})]));
const cw=heading('CONSOLIDADO','CONSOLIDADO DE CALIFICACIONES',['N.º','Estudiante',...Array.from({length:3},(_,i)=>['Formativa P'+(i+1),'Sumativa P'+(i+1),'Final P'+(i+1)]).flat(),'Promedio anual','Observación']);
const qw=heading('CONSOLIDADO CUALITATIVO','CONSOLIDADO CUALITATIVO',['N.º','Estudiante','I período','I cualitativo','II período','II cualitativo','III período','III cualitativo','Observaciones']);
const mw=heading('SUPLETORIO','ACTA DE SUPLETORIOS',['N.º','Estudiante','Promedio anual','Examen supletorio','Final anual','Observación']);
students.forEach((s,i)=>{const outputs=[1,2,3].map(p=>out(s.id,p)),grades=outputs.map(o=>o?.complete?o.total:null),av=annual(grades);cw.addRow([i+1,s.name,...outputs.flatMap(o=>[o?.formative??null,o?.summative??null,o?.total??null]),av,status(av)]);qw.addRow([i+1,s.name,...outputs.flatMap(o=>[o?.total??null,qualitative(o?.total??null)]),[1,2,3].map(p=>row(s.id,p)?.observation||'').filter(Boolean).join(' / ')]);const e=row(s.id,3)?.makeup??null,final=makeup(av,e);mw.addRow([i+1,s.name,av,e,final,final===null?'Pendiente':final>6.99?'APROBADO':'PIERDE AÑO']);});
wb.worksheets.forEach(ws=>ws.eachRow((r,n)=>{r.alignment={vertical:'middle',wrapText:true};r.height=n<=6?22:30;if(n>6){if(n%2)r.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF3F7FB'}};r.eachCell(c=>{if(typeof c.value==='number'&&Number(c.col)>2)c.numFmt='0.00';});}}));return new Uint8Array(await wb.xlsx.writeBuffer());}
