// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
import {sql} from 'drizzle-orm';
export const institutions = sqliteTable('institutions', { id:text('id').primaryKey(), owner:text('owner').notNull(), name:text('name').notNull(), code:text('code').notNull(), year:text('year').notNull(), settings:text('settings').notNull(), created:text('created').notNull() }, t=>[uniqueIndex('institution_code').on(t.code)]);
export const members=sqliteTable('members',{id:text('id').primaryKey(),institution:text('institution').notNull().references(()=>institutions.id),user:text('user'),email:text('email').notNull(),name:text('name').notNull(),role:text('role').notNull(),status:text('status').notNull(),tutorCourses:text('tutor_courses').notNull()},t=>[uniqueIndex('member_email').on(t.institution,t.email),index('member_user').on(t.user)]);
export const records=sqliteTable('records',{id:text('id').primaryKey(),institution:text('institution').notNull().references(()=>institutions.id),kind:text('kind').notNull(),owner:text('owner').notNull(),course:text('course'),payload:text('payload').notNull(),version:integer('version').notNull().default(1),updated:text('updated').notNull(),deleted:integer('deleted').notNull().default(0)},t=>[index('record_scope').on(t.institution,t.kind,t.deleted),uniqueIndex('gradebook_slot').on(t.institution,sql`json_extract(${t.payload}, '$.assignmentId')`,sql`json_extract(${t.payload}, '$.period')`).where(sql`${t.kind} = 'gradebook' AND ${t.deleted} = 0`),uniqueIndex('assignment_slot').on(t.institution,t.course,sql`json_extract(${t.payload}, '$.teacherId')`,sql`json_extract(${t.payload}, '$.subjectId')`).where(sql`${t.kind} = 'assignment' AND ${t.deleted} = 0`)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),institution:text('institution').notNull(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),detail:text('detail').notNull(),created:text('created').notNull()},t=>[index('audit_scope').on(t.institution,t.created)]);
export const connections=sqliteTable('connections',{institution:text('institution').primaryKey(),account:text('account').notNull(),secret:text('secret').notNull(),folder:text('folder'),updated:text('updated').notNull()});
export const oauthStates=sqliteTable('oauth_states',{id:text('id').primaryKey(),user:text('user').notNull(),institution:text('institution').notNull(),verifier:text('verifier').notNull(),expires:integer('expires').notNull()});
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),user:text('user').notNull(),email:text('email').notNull(),name:text('name').notNull(),expires:integer('expires').notNull()});
export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),passwordSalt:text('password_salt').notNull(),created:text('created').notNull()},t=>[uniqueIndex('account_email').on(t.email)]);
export const driveDocuments=sqliteTable('drive_documents',{id:text('id').primaryKey(),institution:text('institution').notNull(),recordId:text('record_id').notNull(),course:text('course').notNull(),owner:text('owner').notNull(),name:text('name').notNull(),url:text('url').notNull(),created:text('created').notNull()},t=>[index('drive_document_scope').on(t.institution,t.course)]);
export const driveGrants=sqliteTable('drive_grants',{id:text('id').primaryKey(),file:text('file').notNull(),member:text('member').notNull(),permission:text('permission').notNull()},t=>[uniqueIndex('drive_grant_slot').on(t.file,t.member)]);
