import {scope,record,canRead,all,one,parse,AppError,log,responseError} from '../../../lib/server';
import {matrixExport} from '../../../lib/matrix-export';
import {result,annual,status,makeup,qualitative,mean} from '../../../lib/calculations';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const q=new URL(req.url).searchParams,inst=q.get('institution')||'',s=await scope(inst),type=q.get('type')||'matrix',id=q.get('id')||'',format=q.get('format')||'xlsx';const r=await record(id,inst);if(!canRead(s,r))throw new AppError('No tienes acceso a este archivo.',403);const institution=await one('SELECT name,year,settings FROM institutions WHERE id=?',inst);institution.settings=JSON.parse(institution.settings);const course=await record(r.course||r.id,inst);let bytes:Uint8Array,mime:string,title:string;let headers:string[]=[],rows:any[][]=[];
if(type==='acta'){if(r.kind!=='meeting')throw new AppError('Junta inválida.');title='Acta '+r.name;headers=['Sección','Contenido'];const labels=await all('SELECT id,name FROM members WHERE institution=?',inst);const memberName=(id:string)=>r.headerSnapshot?.memberLabels?.find((m:any)=>m.id===id)?.name||labels.find(m=>m.id===id)?.name||'Docente';const commitments=(r.snapshot||[]).filter((x:any)=>x.kind==='commitment');const live=r.snapshot?commitments:(await all("SELECT * FROM records WHERE institution=? AND course=? AND kind='commitment' AND deleted=0",inst,r.course)).map(parse).filter(c=>c.meetingId===r.id);rows=[['Institución',r.headerSnapshot?.institution?.name||institution.name],['Año lectivo',r.headerSnapshot?.institution?.year||institution.year],['Curso',r.headerSnapshot?.courseName||course.name],['Fecha y hora',r.date+' '+(r.time||'')],['Tutor',r.tutor||'—'],['Directivo',r.director||'—'],['Asistentes',(r.attendees||[]).map(memberName).join(', ')],['Orden del día',r.agenda||'Sin registro'],['Análisis académico',r.analysis||'Sin registro'],['Acuerdos',r.agreements||'Sin registro'],...live.map((c:any)=>['Compromiso',c.name+' · '+memberName(c.responsible)+' · '+c.due+' · '+c.status]),['Firma del tutor','____________________________'],['Firma del directivo','____________________________']];mime='application/pdf';}
else if(r.kind==='assignment'){const subject=await record(r.subjectId,inst),teacher=await one('SELECT name FROM members WHERE id=? AND institution=?',r.teacherId,inst);const students=(await all("SELECT * FROM records WHERE institution=? AND course=? AND kind='student' AND deleted=0",inst,r.course)).map(parse).sort((a,b)=>a.name.localeCompare(b.name,'es'));const books=(await all("SELECT * FROM records WHERE institution=? AND kind='gradebook' AND json_extract(payload,'$.assignmentId')=? AND deleted=0",inst,r.id)).map(parse);title=(type==='matrix'?'Matriz ':'Consolidado ')+subject.name+' '+course.name;if(type==='matrix'){bytes=await matrixExport(institution,r,course,subject,teacher,students,books);mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';await (await log(inst,s.member.id,'Matriz descargada',id)).run();return new Response(bytes as any,{headers:{'Content-Type':mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(title+'.xlsx'),'Cache-Control':'private, no-store'}});}headers=['N.º','Estudiante','I período','II período','III período','Anual','Estado','I cualitativo','II cualitativo','III cualitativo','Supletorio','Final'];rows=students.map((st,i)=>{const outputs=[1,2,3].map(p=>{const g=books.find(b=>b.period===p),row=g?.rows.find((x:any)=>x.studentId===st.id),o=row?result(row,institution.settings.formative):null;return o?.complete?o.total:null;}),av=annual(outputs),e=books.find(g=>g.period===3)?.rows.find((x:any)=>x.studentId===st.id)?.makeup??null;return [i+1,st.name,...outputs,av,status(av),...outputs.map(qualitative),e,makeup(av,e)];});mime=format==='pdf'?'application/pdf':format==='csv'?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';}
else throw new AppError('Tipo de archivo inválido.');
if(mime==='application/pdf'){const {jsPDF}=await import('jspdf');const pdf=new jsPDF({orientation:headers.length>8?'landscape':'portrait'}),width=pdf.internal.pageSize.getWidth(),height=pdf.internal.pageSize.getHeight(),widths=type==='acta'?[40,width-64]:headers.map((_,i)=>i===1?50:(width-74)/(headers.length-1));let y=18;const header=()=>{pdf.setFontSize(14);pdf.setTextColor(25,66,98);pdf.text(institution.name,12,15);pdf.setFontSize(11);pdf.text(pdf.splitTextToSize(title,width-24),12,23);pdf.setFontSize(8);pdf.setTextColor(50);y=38;let x=12;headers.forEach((h,i)=>{pdf.text(pdf.splitTextToSize(h,widths[i]-2),x,y);x+=widths[i];});y=49;};header();rows.forEach((row,i)=>{const lines=row.map((v,j)=>pdf.splitTextToSize(v==null?'Pendiente':typeof v==='number'?v.toFixed(j===0?0:2):String(v),widths[j]-2));const rowHeight=Math.max(8,...lines.map(l=>l.length*4+3));if(y+rowHeight>height-15){pdf.addPage();header();}if(i%2===0){pdf.setFillColor(242,246,250);pdf.rect(12,y-4,width-24,rowHeight,'F');}let x=12;lines.forEach((l,j)=>{pdf.text(l,x,y);x+=widths[j];});y+=rowHeight;});bytes=new Uint8Array(pdf.output('arraybuffer'));}
else if(mime==='text/csv'){const quote=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"';bytes=new TextEncoder().encode('\uFEFF'+[headers,...rows].map(r=>r.map(quote).join(';')).join('\r\n'));}
else{const ExcelJS=(await import('exceljs')).default,wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Consolidado');ws.addRow([institution.name]);ws.addRow([title,institution.year]);ws.addRow(headers);rows.forEach(r=>ws.addRow(r));ws.getRow(3).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(3).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF122D4B'}};ws.columns=headers.map((h,i)=>({width:i===1?42:18}));ws.views=[{state:'frozen',ySplit:3}];ws.eachRow((r,n)=>{r.alignment={wrapText:true,vertical:'middle'};r.height=25;if(n>3)r.eachCell(c=>{if(typeof c.value==='number'&&Number(c.col)>2)c.numFmt='0.00';});});bytes=new Uint8Array(await wb.xlsx.writeBuffer());}
await (await log(inst,s.member.id,'Archivo descargado',id,{type,format})).run();const ext=mime==='application/pdf'?'pdf':mime==='text/csv'?'csv':'xlsx';return new Response(bytes as any,{headers:{'Content-Type':mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(title+'.'+ext),'Cache-Control':'private, no-store'}});
}catch(e){return responseError(e);}}
