import {scope,record,canRead,all,one,parse,AppError,log,responseError} from '../../../lib/server';
import {matrixExport} from '../../../lib/matrix-export';
import {result,annual,status,makeup,qualitative} from '../../../lib/calculations';
export const dynamic='force-dynamic';

const excelMime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const wordMime='application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const quote=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"';

function printable(v:any,numeric=false){return v==null?'Pendiente':numeric&&typeof v==='number'?v.toFixed(2):String(v);}
function logoAsset(logo:any){const m=String(logo||'').match(/^data:image\/(png|jpeg);base64,(.+)$/);return m?{base64:m[2],extension:m[1]==='png'?'png':'jpeg',data:Uint8Array.from(atob(m[2]),x=>x.charCodeAt(0))}:null;}
async function documentExport(institution:any,title:string,subtitle:string,headers:string[],rows:any[][]){
  const docx:any=await import('docx'),{Document,Packer,Paragraph,Table,TableCell,TableRow,TextRun,HeadingLevel,WidthType,ShadingType,ImageRun,AlignmentType}=docx,logo=logoAsset(institution.settings.logo);
  const cell=(text:any,bold=false,shade?:string)=>new TableCell({shading:shade?{fill:shade,type:ShadingType.CLEAR}:undefined,children:[new Paragraph({children:[new TextRun({text:printable(text),bold,color:bold?'FFFFFF':undefined})]})]});
  const table=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:headers.map(h=>cell(h,true,'123B63'))}),...rows.map(row=>new TableRow({children:row.map(v=>cell(v))}))]});
  const doc=new Document({sections:[{children:[...(logo?[new Paragraph({alignment:AlignmentType.RIGHT,children:[new ImageRun({data:logo.data,type:logo.extension==='png'?'png':'jpg',transformation:{width:70,height:70}})]})]:[]),new Paragraph({text:institution.name,heading:HeadingLevel.TITLE}),new Paragraph({text:title,heading:HeadingLevel.HEADING_1}),new Paragraph({text:subtitle}),table,new Paragraph({text:'Documento generado por Profe. Byron Gestión Docente · '+new Date().toLocaleDateString('es-EC')})]}]});
  return new Uint8Array(await Packer.toBuffer(doc));
}
async function spreadsheetExport(institution:any,title:string,subtitle:string,headers:string[],rows:any[][]){
  const ExcelJS=(await import('exceljs')).default,wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Informe'),total=Math.max(headers.length,1),navy='FF123B63',light='FFF2F6FA',border={style:'thin',color:{argb:'FFD8E3EC'}};
  wb.creator='Profe. Byron Gestión Docente';wb.company='Profe. Byron Gestión Docente';wb.created=new Date();ws.properties={defaultRowHeight:21};ws.sheetProperties.pageSetUpPr={fitToPage:true};
  ws.addRow(['PROFE. BYRON · GESTIÓN DOCENTE']);ws.mergeCells(1,1,1,total);ws.getCell('A1').font={bold:true,size:15,color:{argb:'FFFFFFFF'}};ws.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:navy}};ws.getRow(1).height=30;
  ws.addRow([institution.name]);ws.mergeCells(2,1,2,total);ws.getCell('A2').font={bold:true,size:13,color:{argb:navy}};ws.getRow(2).height=24;
  ws.addRow([title]);ws.mergeCells(3,1,3,total);ws.getCell('A3').font={bold:true,size:11,color:{argb:'FF1F5B88'}};ws.addRow([subtitle+' · Generado: '+new Date().toLocaleDateString('es-EC')]);ws.mergeCells(4,1,4,total);ws.getCell('A4').font={italic:true,size:10,color:{argb:'FF587087'}};ws.addRow([]);
  const header=ws.addRow(headers);header.font={bold:true,color:{argb:'FFFFFFFF'}};header.fill={type:'pattern',pattern:'solid',fgColor:{argb:navy}};header.height=27;header.alignment={vertical:'middle',horizontal:'center',wrapText:true};rows.forEach(row=>ws.addRow(row));
  const logo=logoAsset(institution.settings.logo);if(logo){try{const image=wb.addImage({base64:logo.base64,extension:logo.extension});ws.addImage(image,{tl:{col:Math.max(0,total-1),row:0},ext:{width:58,height:58}});}catch{}}
  ws.columns=headers.map((h,i)=>{const max=Math.max(h.length,...rows.map(row=>String(row[i]??'').length)),wide=/estudiante|asignatura|observaci|justific|detalle|acuerdo/i.test(h);return {width:wide?Math.min(48,Math.max(24,max+4)):Math.min(24,Math.max(12,max+3))};});ws.views=[{state:'frozen',ySplit:6}];ws.autoFilter={from:{row:6,column:1},to:{row:Math.max(6,6+rows.length),column:total}};
  ws.pageSetup={orientation:headers.length>7?'landscape':'portrait',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:0.25,right:0.25,top:0.5,bottom:0.5,header:0.2,footer:0.2}};ws.headerFooter.oddFooter='Profe. Byron Gestión Docente · Página &P de &N';
  ws.eachRow((row,n)=>{row.alignment={wrapText:true,vertical:'middle'};if(n>6){row.height=30;if(n%2===1)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:light}};row.eachCell((cell:any,col:number)=>{cell.border={top:border,bottom:border,left:border,right:border};if(typeof cell.value==='number')cell.numFmt='0.00';const heading=headers[col-1]||'',value=String(cell.value||'').toLowerCase();if(/estado/.test(heading)&&value)cell.font={bold:true,color:{argb:value.includes('aprob')||value.includes('cumpl')?'FF16735C':value.includes('reprob')||value.includes('no cumpl')?'FFB0444D':'FF8A6A22'}};});}else if(n===6)row.eachCell((cell:any)=>cell.border={top:border,bottom:border,left:border,right:border});});return new Uint8Array(await wb.xlsx.writeBuffer());
}
async function pdfExport(institution:any,title:string,subtitle:string,headers:string[],rows:any[][]){
  const {jsPDF}=await import('jspdf'),pdf=new jsPDF({orientation:headers.length>7?'landscape':'portrait'}),width=pdf.internal.pageSize.getWidth(),height=pdf.internal.pageSize.getHeight(),widths=headers.map((_,i)=>i===1?Math.min(55,(width-24)/2):(width-24-Math.min(55,(width-24)/2))/(headers.length-1));let y=18;
  const header=()=>{pdf.setFillColor(18,59,99);pdf.rect(0,0,width,34,'F');try{if(institution.settings.logo?.startsWith('data:image/png'))pdf.addImage(institution.settings.logo,'PNG',width-31,5,23,23);}catch{}pdf.setTextColor(255);pdf.setFontSize(14);pdf.text(institution.name,12,13);pdf.setFontSize(11);pdf.text(pdf.splitTextToSize(title,width-52),12,21);pdf.setFontSize(8);pdf.text(pdf.splitTextToSize(subtitle,width-52),12,28);pdf.setTextColor(35);y=43;let x=12;headers.forEach((h,i)=>{pdf.setFontSize(7);pdf.text(pdf.splitTextToSize(h,widths[i]-2),x,y);x+=widths[i];});y+=8;};header();
  rows.forEach((row,index)=>{const lines=row.map((v,i)=>pdf.splitTextToSize(printable(v,i>1),widths[i]-2));const rowHeight=Math.max(8,...lines.map(l=>l.length*4+3));if(y+rowHeight>height-16){pdf.addPage();header();}if(index%2===0){pdf.setFillColor(242,246,250);pdf.rect(12,y-4,width-24,rowHeight,'F');}let x=12;lines.forEach((line,i)=>{pdf.setFontSize(7);pdf.text(line,x,y);x+=widths[i];});y+=rowHeight;});for(let i=1;i<=pdf.getNumberOfPages();i++){pdf.setPage(i);pdf.setTextColor(80);pdf.setFontSize(7);pdf.text('Profe. Byron Gestión Docente · Página '+i+' de '+pdf.getNumberOfPages(),12,height-7);}return new Uint8Array(pdf.output('arraybuffer'));
}

export async function GET(req:Request){try{
  const q=new URL(req.url).searchParams,inst=q.get('institution')||'',s=await scope(inst),type=q.get('type')||'matrix',id=q.get('id')||'',format=q.get('format')||'xlsx';
  const r=await record(id,inst);if(!canRead(s,r))throw new AppError('No tienes acceso a este archivo.',403);
  const institution=await one('SELECT name,year,settings FROM institutions WHERE id=?',inst);institution.settings=JSON.parse(institution.settings);
  let title='',subtitle='Año lectivo '+institution.year,headers:string[]=[],rows:any[][]=[],course:any=null;
  if(type==='acta'){
    if(r.kind!=='meeting')throw new AppError('Junta inválida.');course=await record(r.course,inst);title='Acta de junta de curso · '+r.name;subtitle='Curso: '+course.name+' · '+institution.year+' · '+r.date+' '+(r.time||'');headers=['Sección','Detalle'];const labels=await all('SELECT id,name FROM members WHERE institution=?',inst),memberName=(memberId:string)=>r.headerSnapshot?.memberLabels?.find((m:any)=>m.id===memberId)?.name||labels.find(m=>m.id===memberId)?.name||'Docente',commitments=r.snapshot?(r.snapshot||[]).filter((x:any)=>x.kind==='commitment'):(await all("SELECT * FROM records WHERE institution=? AND course=? AND kind='commitment' AND deleted=0",inst,r.course)).map(parse).filter(c=>c.meetingId===r.id);rows=[['Institución',institution.name],['Tutor',r.tutor||'—'],['Directivo',r.director||'—'],['Asistentes',(r.attendees||[]).map(memberName).join(', ')||'Sin registro'],['Orden del día',r.agenda||'Sin registro'],['Análisis académico',r.analysis||'Sin registro'],['Acuerdos',r.agreements||'Sin registro'],...commitments.map((c:any)=>['Compromiso',c.name+' · Responsable: '+memberName(c.responsible)+' · Fecha: '+c.due+' · '+c.status]),['Firmas','Tutor: ____________________    Directivo: ____________________']];
  } else if(type==='student'){
    if(r.kind!=='student')throw new AppError('Estudiante inválido.');course=await record(r.course,inst);const assignments=(await all("SELECT * FROM records WHERE institution=? AND course=? AND kind='assignment' AND deleted=0",inst,r.course)).map(parse),subjectFilter=q.get('assignment')||'',selected=subjectFilter?assignments.filter(a=>a.id===subjectFilter):assignments;if(subjectFilter&&!selected.length)throw new AppError('Asignatura no disponible.');const subjects=(await all("SELECT * FROM records WHERE institution=? AND kind='subject' AND deleted=0",inst)).map(parse),members=await all('SELECT id,name FROM members WHERE institution=?',inst),books=(await all("SELECT * FROM records WHERE institution=? AND course=? AND kind='gradebook' AND deleted=0",inst,r.course)).map(parse);title=(subjectFilter?'Boletín de calificaciones':'Informe integral de rendimiento')+' · '+r.name;subtitle='Estudiante: '+r.name+(r.identifier?' · ID: '+r.identifier:'')+' · Curso: '+course.name+' · '+institution.year;headers=['Asignatura','Docente','I período','II período','III período','Promedio anual','Estado','Final'];rows=selected.map(a=>{const outputs=[1,2,3].map(p=>{const book=books.find(b=>b.assignmentId===a.id&&b.period===p),row=book?.rows.find((x:any)=>x.studentId===r.id);return row?result(row,institution.settings.formative):null;}),grades=outputs.map(o=>o?.total??null),av=annual(grades),last=books.find(b=>b.assignmentId===a.id&&b.period===3)?.rows.find((x:any)=>x.studentId===r.id),subject=subjects.find(x=>x.id===a.subjectId),teacher=members.find(x=>x.id===a.teacherId);return [subject?.name||'Asignatura',teacher?.name||'Docente',...grades,av,status(av),makeup(av,last?.makeup??null)];});
  } else if(r.kind==='assignment') {
    course=await record(r.course,inst);const subject=await record(r.subjectId,inst),teacher=await one('SELECT name FROM members WHERE id=? AND institution=?',r.teacherId,inst),students=(await all("SELECT * FROM records WHERE institution=? AND course=? AND kind='student' AND deleted=0",inst,r.course)).map(parse).sort((a,b)=>a.name.localeCompare(b.name,'es')),books=(await all("SELECT * FROM records WHERE institution=? AND kind='gradebook' AND json_extract(payload,'$.assignmentId')=? AND deleted=0",inst,r.id)).map(parse);title=(type==='matrix'?'Matriz de calificaciones':'Consolidado de calificaciones')+' · '+subject.name;subtitle='Curso: '+course.name+' · Docente: '+teacher.name+' · '+institution.year;if(type==='matrix'){const bytes=await matrixExport(institution,r,course,subject,teacher,students,books);await (await log(inst,s.member.id,'Matriz descargada',id)).run();return new Response(bytes as any,{headers:{'Content-Type':excelMime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(title+'.xlsx'),'Cache-Control':'private, no-store'}});}headers=['N.º','Estudiante','I período','II período','III período','Promedio anual','Estado','I cualitativo','II cualitativo','III cualitativo','Supletorio','Final'];rows=students.map((st,i)=>{const outputs=[1,2,3].map(p=>{const g=books.find(b=>b.period===p),row=g?.rows.find((x:any)=>x.studentId===st.id);return row?result(row,institution.settings.formative):null;}),grades=outputs.map(o=>o?.total??null),av=annual(grades),e=books.find(g=>g.period===3)?.rows.find((x:any)=>x.studentId===st.id)?.makeup??null;return [i+1,st.name,...grades,av,status(av),...grades.map(qualitative),e,makeup(av,e)];});
  } else throw new AppError('Tipo de archivo inválido.');
  let bytes:Uint8Array,mime:string,ext:string;if(format==='pdf'){bytes=await pdfExport(institution,title,subtitle,headers,rows);mime='application/pdf';ext='pdf';}else if(format==='docx'){bytes=await documentExport(institution,title,subtitle,headers,rows);mime=wordMime;ext='docx';}else if(format==='csv'){bytes=new TextEncoder().encode('\uFEFF'+[headers,...rows].map(row=>row.map(quote).join(';')).join('\r\n'));mime='text/csv';ext='csv';}else{bytes=await spreadsheetExport(institution,title,subtitle,headers,rows);mime=excelMime;ext='xlsx';}await (await log(inst,s.member.id,'Archivo descargado',id,{type,format})).run();return new Response(bytes as any,{headers:{'Content-Type':mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(title+'.'+ext),'Cache-Control':'private, no-store'}});
}catch(e){return responseError(e);}}
